### ISSUE TITLE
cmake error on osx after recent changes

### ISSUE THREAD

**Issue by n9yty** [Ultimaker/cura-build#109]
I had built this before, but I updated from the repo and the cmake configure step now fails:

CMake Error at CMakeLists.txt:23 (get_filename_component):
  get_filename_component unknown component CACHE

CMake Error at projects/CuraEngine.cmake:1 (find_package):
  By not providing "FindArcus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Arcus", but
  CMake did not find one.

  Could not find a package configuration file provided by "Arcus" (requested
  version 1.1) with any of the following names:

    ArcusConfig.cmake
    arcus-config.cmake

  Add the installation prefix of "Arcus" to CMAKE_PREFIX_PATH or set
  "Arcus_DIR" to a directory containing one of the above files.  If "Arcus"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:61 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/n9yty/Projects/cura/cura-build/build/CMakeFiles/CMakeOutput.log".

**Comment by Ghostkeeper** [comment]
We recently merged a huge branch into master here. It splits up the build process in two: One for dependencies and one for Cura itself.

It now needs to have this repository built first (or the dependencies separately installed): https://github.com/Ultimaker/cura-build-environment

This was done to allow building Cura automatically and quickly without needing to re-compile all those dependencies again. I don't know the exact circumstances that result in your error, but that seems a likely candidate. If you need help compiling cura-build-environment, I'm sure @awhiemstra is willing to help.

**Comment by awhiemstra** [comment]
Arcus was removed from cura-build and moved to cura-build-environment due to it needing to be built with MSVC and because I want to decouple its release process from Cura. We are planning to distribute binary releases of Arcus so that you can just install that on top of an existing Python and be done with it. Unfortunately we are not there yet, so for now you will either need to compile it manually, use cura-build-environment or manually point CuraEngine's cmake at the right location for Arcus. This last step can be done by changing the Arcus_DIR variable in the CMake configuration in $build_dir/CuraEngine-prefix/src/CuraEngine-build

**Comment by n9yty** [comment]
Build it with MSVC on MacOS? I will look for the other repo, but you also might want to update the build notes to reflect this.

**Comment by awhiemstra** [comment]
No, on Windows it needs to be built with MSVC. On Mac/Linux the same compiler can be used for everything so it not so much of a problem there.

**Comment by yingzhang1109** [comment]
make -j6 is not working on windows @awhiemstra

**Comment by Ghostkeeper** [comment]
Try `nmake` instead of `make`.

**Comment by OutsourcedGuru** [comment]
For what it's worth, the error appears to be moved now into the dependencies repository, see [this issue #32](https://github.com/Ultimaker/cura-build-environment/issues/32).

**Comment by Ghostkeeper** [comment]
So I recently found out what caused this sort of error, "unknown component CACHE", (courtesy of awhiemstra) that might allow for some insight in how to debug this, because the error is cryptic.

So what happens is that we call `get_filename_component(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} ABSOLUTE CACHE FORCE)`. This should store the result in `CMAKE_PREFIX_PATH`, get the source string from `${CMAKE_PREFIX_PATH}`, get the component `ABSOLUTE` and cache and force it. But when `${CMAKE_PREFIX_PATH}` is empty, every parameter shifts one to the left, so to say and it'll interpret it as if it should get the component `CACHE` which is not a component that CMake knows of.

**Comment by Bostwickenator** [comment]
Trying to set this mess up. Then I'll make a docker image that can run the build.

**Comment by Ghostkeeper** [comment]
I'll consider this as answered then.
