### ISSUE TITLE
Switch to AppImage Type 2

### ISSUE THREAD

**Issue by TheAssassin** [Ultimaker/cura-build#136]
*See https://github.com/Ultimaker/Cura/issues/2506*

Currently, the Cura AppImages (just checked the 2.7.0 release) are type 1. This type is deprecated for good reasons. Type 2 has been around for a while, and aside from being more advanced and efficient, there's better tooling available which makes building them easier.

A few advantages:

 - More efficient due to use of squashfs instead of ISO 9660
 - Better ecosystem
   - especially important: [AppImageUpdate](https://github.com/AppImage/AppImageUpdate) -- allows for easy updating of AppImages (utilizing highly efficient binary delta updates) that ship with so-called [update information](https://github.com/AppImage/AppImageUpdate#example-how-to-make-your-app-self-updateable), I'd really recommend implementing this feature
   - [appimagetool](https://github.com/AppImage/AppImageKit/tree/appimagetool/master#appimagetool-usage), replacement for AppImageAssistant, faster and easier to use
   - [linuxdeployqt](https://github.com/probonopd/linuxdeployqt), a really easy to use advanced application for preparing AppDirs for any kind of application, not limited to Qt, but can also bundle Qt plugins with little to no effort
   - provides replacements for the hackish solutions in [this repository](https://github.com/AppImage/AppImages) which really shouldn't be used any more
 - Can be signed to provide authentication and integrity, although this hasn't been developed very far (help welcome, as usual)
 - More standalone (e.g., the AppImages can be extracted and manually mounted without additional tools)
 - ... and a few other features (@probonopd could provide some additional details)

I'd really recommend switching to type 2. If you need help, make sure to visit the AppImage IRC channel ([#appimage](https://webchat.freenode.net/?channels=appimage) on Freenode), we'll do our best to help.

You can check the version with this command:

```
> dd if=Cura-2.7.0.AppImage  bs=1 count=4 skip=8 | hexdump
0000000 4941 0001
                ^ version 1

# for comparison
> dd if=AppImageUpdate-x86_64.AppImage bs=1 count=4 skip=8 | hexdump
0000000 4941 0002
                ^ version 2
```

**Comment by Ghostkeeper** [comment]
This is not trivial, since our build system fetches the .tar.gz of this repository and tries to build that. Currently that works with CMake, building AppImageKit version 6. But in version 7 they switched away from CMake and instead use a shell script, build.sh. This shell script fails because the .tar.gz file is not a Git repository and it tries to fetch subrepositories.

**Comment by probonopd** [comment]
@Ghostkeeper do you really need to build AppImageKit yourself? You could also mirror https://github.com/AppImage/AppImageKit/releases/tag/continuous and use that.

**Comment by TheAssassin** [comment]
Furthermore, the current AppImageKit branch `appimagetool/master` contains a basic `CMakeLists.txt` which at least can be used to build appimagetool.

**Comment by daid** [comment]
A reason for keeping to type 1 is that type 1 has possibly more wide spread support? (question mark, because I don't know). It would kinda suck if you could install Cura before, and all of a sudden after an update you can no longer.

"Type 2 has been around for a while" is a big vague on the timeline. While "Back when we did the initial AppImage work, the v2 format was only a discussion item." indicates that the v2 format is still pretty new.

**Comment by TheAssassin** [comment]
As far as I can tell, there's no systems or integrations or any software which supports type 1 but not type 2. Distributions have not added special AppImage support yet. Neither has any of the companion tools provided by the AppImage project only support for a single type, except for the two different packaging tools (which are revision specific of course), and AppImageUpdate (the feature has been added in type 2). There won't be any consequences you'd have to face other than advantages.

> "Type 2 has been around for a while" is a big vague on the timeline.

Well, consider it stable, well tested, and widespread. There are not too many projects left relying on type 1.

> "Type 2 has been around for a while" is a big vague on the timeline. While "Back when we did the initial AppImage work, the v2 format was only a discussion item." indicates that the v2 format is still pretty new.

Where did you find that quote? It is anything but [new](https://github.com/AppImage/AppImageKit/commits/appimagetool/master?after=3329f42f0c5d13b754e1a73f877725846682ded7+594).

**Comment by daid** [comment]
That quote came from the other issue reported on the Cura repo.

A year old is quite new in my book. Which is why the terms "new" and "old" are just an opinion, and hard to make any judgement with. Same for "widespread" and "well tested", that's like... your opinion man. Dates, numbers, hard data, facts are much nicer ;-)

(Note, I'm just a random idiot, not the person making the call to switch to the v2 format or not)

**Comment by TheAssassin** [comment]
By the way, in an idea world, you could build alpha/beta AppImages right in the CI, and upload them somewhere (many use https://transfer.sh). That allows for rapid feedback.

**Comment by probonopd** [comment]
@TheAssassin check this out: 
http://software.ultimaker.com/Cura_open_beta/?C=M;O=D - latest is from today :+1:

**Comment by TheAssassin** [comment]
@probonopd that's still a type 1 build.

As seen in [the original issue](https://github.com/Ultimaker/Cura/issues/2506), @Ghostkeeper made a [commit](https://github.com/Ultimaker/cura-build-environment/commit/efc0654a9567d206d2c518ece53c6da8281739cb). @Ghostkeeper, mind to tell us what's the current state of this issue? Great to see progress, but it appears it hasn't reached the beta builds yet.

**Comment by Ghostkeeper** [comment]
I shouldn't have made that commit. I saw on the build server that it broke stuff, then investigated why (there is no CMake any more), and reverted that commit. I didn't even consider platform support which is also bad of me.

The status of this issue is that it effectively fell into the water because of that.

We do build all of our dependencies from source as well, with a few exceptions because the build is too hard (numpy and Qt on Windows, iirc).

**Comment by Ghostkeeper** [comment]
Eventually we're still going to have to update some day. It's a bad state we're in right now to depend on an old version of software because we can't get the new one to work yet. The speed improvements and the signing are definitely interesting. But for now there's not yet enough incentive to spend much time on it.

**Comment by probonopd** [comment]
> we can't get the new one to work yet

May I help? What exactly can't you get to work?

**Comment by TheAssassin** [comment]
It should be possible to build appimagetool in some way in your build process, it isn't _that_ hard and we'd really like to see you upgrade to the new format. Type 1 is in maintenance mode, new tools don't really take care any more etc., so the upgrade will be mandatory some day anyway.

**Comment by probonopd** [comment]
> It should be possible to build appimagetool in some way 

Not even necessary...

**Comment by TheAssassin** [comment]
> Not even necessary...

@probonopd that was mentioned a few times, but the team mentioned that they'd prefer to build it themselves for some reason.

**Comment by TheAssassin** [comment]
@Ghostkeeper our build system is now based on CMake. Please revise this issue, I hope you can make the switch now.

**Comment by Ghostkeeper** [comment]
It built successfully on my local computer, at least :smiley: No more sudo requirements.

**Comment by thopiekar** [comment]
You mean with AppImageKit 10?
Good timing, because I'm working on cura-build-environment to build everything from scratch.
Is there a PR with your changes to make it work with a more recent AppImageKit?

**Comment by Ghostkeeper** [comment]
Yes, 10. Not yet. I'll make one. I'm currently trying to build cura-build-environment locally so that takes a while.

**Comment by TheAssassin** [comment]
@Ghostkeeper please remember we don't really make releases, so it's better to use the latest available verison. Also, @thopiekar found a bug while trying to build AppImageKit, see https://github.com/AppImage/AppImageKit/issues/666.

**Comment by Ghostkeeper** [comment]
@thopiekar See the `appimage_v2` branch on cura-build-environment.

**Comment by thopiekar** [comment]
Thanks! I hope I get a build with my cura-build-environment done soon.
I'm currently testing with one thread (make -j1), which takes > 8h to build. Compared to the current Ultimaker/cura-build-environement your build @Ghostkeeper can be rated as "fast" :rofl:

**Comment by TheAssassin** [comment]
We've found a bug in your latest type 1 AppImage that prevents Cura from being handled using libappimage properly. See https://github.com/AppImage/AppImageKit/issues/790.
With type 2, this wouldn't ever have been an issue.

How far have you got with the transition to type 2?

**Comment by Ghostkeeper** [comment]
I got stuck back then because Squashfuse was not supported on CentOS 6 which we are using for our build server. I see though that you've since removed that requirement from the global build file so I'll try again.

**Comment by Ghostkeeper** [comment]
Status update: I got stuck again because AppImageKit now requires GLib 2.40 which is also not supported by CentOS 6. I added GLib to the build environment so that it gets built from source (2.56.1). This worked on my laptop but again on CentOS 6 this requires a newer version of AutoTools (1.13) which is not supported by any CentOS version. They're stuck on 1.11. I didn't take the effort yet to build Autoconf from source because it's a bit silly. Alternatively we could try writing a CMake script for GLib but that seems like a lot of work.

**Comment by TheAssassin** [comment]
@Ghostkeeper you could save yourself so much time by just using our AppImages...

If you want to save yourself some time, you can use our Docker container build environment (https://github.com/AppImage/AppImageBuild).

**Comment by probonopd** [comment]
We are using CentOS 6.x in our Docker container, too. So possibly you can copy&paste from there.

**Comment by TheAssassin** [comment]
Any updates to this? It'd be great after a year to have a type 2 AppImage.

I just download new releases, extract them, and rebuild them using appimagetool now to have type 2 AppImages. I run appimagetool with `VERSION=3.4.1 appimagetool...` to also have a version number in my launcher, etc.

**Comment by t-paul** [comment]
That [Type 2 AppImage](https://github.com/TheAssassin/cura-type2-appimages/releases) (Cura 3.4.1) works fine on Debian/Testing.

**Comment by Taz8du29** [comment]
I'd appreciate a port to type 2 AppImages, too.

**Comment by talldonkey** [comment]
+1 I have a corporate-issued pixelbook and only Type2 AppImages, when extracted work on Pixelbook via Linux VM/Crostini.

**Comment by Ghostkeeper** [comment]
This has now been implemented. Cura 4.2 will be the first build that has AppImage Type 2.
