### ISSUE TITLE
Missing branches and release tags

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/cura-build#144]
Missing a tag for 3.0.4 and a branch for 3.0.

**Comment by thopiekar** [comment]
Same in https://github.com/Ultimaker/cura-build-environment

**Comment by ChrisTerBeke** [comment]
I don't think we do tags for the build scripts and environment?

**Comment by thopiekar** [comment]
Really? 😬 
But then why is there a 3.0.3 tag?

**Comment by Ghostkeeper** [comment]
We don't usually do branches on the build repositories because the build script itself accepts a parameter of which branch to build, unless a certain branch needs different dependencies that we don't yet want to introduce in master (or vice versa). We should tag the releases though in order to be able to reproduce them. I've often forgotten that...
