### ISSUE TITLE
how to deal with undefined symbol??

### ISSUE THREAD

**Issue by winyluo** [Ultimaker/cura-build#157]
Traceback (most recent call last):
  File "cura_app.py", line 84, in <module>
    import Arcus #@UnusedImport
ImportError: /usr/local/lib/libArcus.so.3: undefined symbol: _ZN6google8protobuf8compiler8Importer6ImportERKSs

**Comment by Ghostkeeper** [comment]
Undefined symbol means that something asks for a property/class/function but can't find it. In this case it's libArcus asking for Protobuf. Usually it means that either:

* The object files are missing, or
* The dynamically linked library is not compiled using the same compiler as whatever it's linked to, or
* The headers don't match up with the object files.

See also https://www.ics.com/designpatterns/book/commonlinkererrors.html

**Comment by LipuFei** [comment]
@winyluo It can be that your `libArcus` is compiled against the dynamic library of `protobuf`. When you load `Arcus` in Python, it tries to load the dynamic library of `protobuf` and call the corresponding functions. The problem could be that:
 - your dynamic `protobuf` library is not available, or
 - you have upgraded your dynamic `protobuf` library, which is no longer binary compatible with the version your `libArcus` was compiled against.
I would suggest to recompile and install your libArcus and check the logs to make sure that it is compiled against the correct libraries.

I'll close this issue due to inactivity for now.
