### ISSUE TITLE
Why is my cbe image not running? 

### ISSUE THREAD

**Issue by sunheat** [Ultimaker/cura-build#268]
I think I was able to successfully build cbe image, the last few lines on the terminal output goes as follows:
```
Step 31/31 : ENTRYPOINT ["/docker-entrypoint.sh"]
 ---> Running in bcd409a602c2
Removing intermediate container bcd409a602c2
 ---> b71266bb69fd
Successfully built b71266bb69fd
```
How do I start it?

Here's the list of images. I didn't tag the image when running docker build because I think there is some default tag and the one I chose was different. I was going to tag it the default name later when I figure things out. At current I have not figured things out.
```
REPOSITORY                         TAG       IMAGE ID       CREATED        SIZE
<none>                             <none>    b71266bb69fd   20 hours ago   2.2GB
<none>                             <none>    c14758cd738d   20 hours ago   27.8GB
ultimaker/cura-build-environment   latest    bd7c2e7d378b   4 days ago     2.14GB
centos                             centos7   eeb6ee3f44bd   2 months ago   204MB
```
So apparently I tried to start the first image in a container, there was no terminal output nor was there a running container after docker run. I did the same on the second image, there was a bunch of terminal outputs, looks like setting env var's. After that, no image remained running.

How do I run the docker image that was built and how do I get inside it so I can build Cura?

And do I need to build CuraEngine separately or cura-build inside a working cura-build-environment is enough?

I am sorry if these questions are too basic. I am from a Java background and have a beginner's knowledge on Python. I have not used Docker before. I thought this was more Python until I realized that it is more native than I thought...

**Comment by Ghostkeeper** [comment]
So for some background, we made a split between cura-build and cura-build-environment because many of the dependencies take a lot of time and disk space to build, yet they don't often change. So cura-build contains Ultimaker's own repositories that often change with Cura, while cura-build-environment contains all of Cura's 3rd party dependencies and some of Ultimaker's repositores that don't often change (e.g. libArcus).

By running the cura-build-environment docker image, you should now have a Linux container that has all of the libraries installed that are needed to build Cura. But you didn't build Cura yet.

To build Cura, you'd have to run the [build.sh](https://github.com/Ultimaker/cura-build/blob/master/docker/linux/build.sh) script from this repository. It should find the Docker image you made from the cura-build-environment and continue from there. It executes a script inside of that docker container to build Cura.

The output of the build will be a .AppImage containing all of Cura (front-end and CuraEngine). It will be placed in `${CURA_APPIMAGES_OUTPUT_DIR}` inside of the Docker container. You'd need to use other Docker commands to copy it out, or go into the shell there and scp it or something.

> How do I run the docker image that was built and how do I get inside it so I can build Cura?

Answering this directly in case it's not clear: The build.sh script in this repository will attempt to run a shell script inside of that Docker container. The shell script creates an .AppImage file that is Cura. Once the shell script is terminated, you're done.

> And do I need to build CuraEngine separately or cura-build inside a working cura-build-environment is enough?

No, that's not necessary. Cura-build will do that.

> I am sorry if these questions are too basic.

No worries! Build systems like these are very complex, and starting out with Docker at the same time isn't exactly the easiest way to learn.

I'll close this question for now, but if you have more questions feel free to ask them. We can reopen the ticket if necessary.
