### ISSUE TITLE
SIP API 11.3

### ISSUE THREAD

**Issue by mhk3000** [Ultimaker/cura-build#40]
Hello,

I am getting the following error on Mac OSX 11.11 when running cura_app.py.
`RuntimeError: the sip module implements API v11.0 to v11.2 but the Arcus module requires API v11.3`

I have installed SIP 4.18. Which version of SIP are we suppose to run

**Comment by Ghostkeeper** [comment]
I have version 4.16.6 on this computer (which is Ubuntu). I don't think having v4.18 should be a problem.

**Comment by thopiekar** [comment]
My own packaging at launchpad uses SIP 4.17 (Ubuntu Xenial). Works here great, too.

**Comment by LipuFei** [comment]
@mhk3000 The error suggests that when you run `cura_app.py`, the `sip` python loaded is some version <4.18, while your Arcus is compiled against `4.18`. Please check if the `sip` module your python loaded is the correct one. For example, you can run the following command:
```
C:\Users\l.fei>python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sip
>>> sip.__file__
'C:\\workspace\\installations\\python\\3.7.1\\lib\\site-packages\\sip.pyd'
>>>
```
This shows that with my current environment setup, when I run `python` and `import sip`, it will load the `sip` module located in `C:\\workspace\\installations\\python\\3.7.1\\lib\\site-packages\\sip.pyd`. Compare this with where the sip module your Arcus is compiled against see if there's a mismatch.

I'll close this issue for now due to inactivity.
