### ISSUE TITLE
Make cura-build depend on GetText

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/cura-build#79]
At the moment we need to copy our translated and compiled .mo-files by hand into cura-binary-data, but it should be possible to generate them during build.

I'm sure there is a way to install gettext on OSX and for Windows you can find:
- http://gnuwin32.sourceforge.net/packages/gettext.htm

**Comment by Ghostkeeper** [comment]
If I recall, it was an explicit choice of @awhiemstra to not make the CMakeLists.txt script require GetText. This was to reduce the number of dependencies of the build system and because the tool is originally only made for Linux.

For Windows there is also https://github.com/mlocati/gettext-iconv-windows . In fact, there are a ton of people who made ports.

**Comment by thopiekar** [comment]
I just don't understand why we can't add gettext here. We are rebuilding protobuf, install dependencies via pip and add new dependencies here, but we don't install GetText?
I think it is a dependency which is needed for our software like any other :confused:
